/*** IMPORTS ***/
#![allow(unused_imports)]
#![allow(dead_code)]
mod ftyp;
mod mdat;
mod free;
mod skip;
mod pdin;
mod moov;
mod mvhd;
mod trak;
mod tkhd;
mod tref;
mod trgr;
mod mdia;
mod mdhd;
mod hdlr;
mod minf;
mod nmhd;
mod elng;
mod stbl;
mod stsd;
mod stdp;
mod stts;
mod ctts;
mod cslg;
mod stss;
mod stsh;
mod sdtp;
mod edts;
mod elst;
mod dinf;
mod dref;
mod stsz;
mod stz2;
mod stsc;
mod stco;
mod co64;
mod padb;
mod subs;
mod saiz;
mod saio;
mod mvex;
mod mehd;
mod trex;
mod moof;
mod mfhd;
mod traf;
mod tfhd;
mod trun;
mod mfra;
mod tfra;
mod mfro;
mod tfdt;
mod leva;
mod trep;
mod assp;
mod sbgp;
mod sgpd;
mod udta;
mod cprt;
mod tsel;
mod kind;
mod meta;
mod xml;
mod bxml;
mod iloc;
mod pitm;
mod ipro;
mod iinf;
mod meco;
mod mere;
mod idat;
mod iref;
mod sinf;
mod frma;
mod schm;
mod schi;
mod fiin;
mod paen;
mod fpar;
mod fecr;
mod segr;
mod gitn;
mod fire;
mod strk;
mod stri;
mod strd;
mod stsg;
mod rinf;
mod stvi;
mod styp;
mod sidx;
mod ssix;
mod prft;
mod cinf;
mod srpp;
mod feci;
mod vmhd;
mod smhd;
mod chnl;
mod dmix;
mod ludt;
mod hmhd;

pub use self::ftyp::Ftyp;
pub use self::mdat::Mdat;
pub use self::free::Free;
pub use self::skip::Skip;
pub use self::pdin::Pdin;
pub use self::moov::Moov;
pub use self::mvhd::Mvhd;
pub use self::trak::Trak;
pub use self::tkhd::Tkhd;
pub use self::tref::Tref;
pub use self::trgr::Trgr;
pub use self::mdia::Mdia;
pub use self::mdhd::Mdhd;
pub use self::hdlr::Hdlr;
pub use self::minf::Minf;
pub use self::nmhd::Nmhd;
pub use self::elng::Elng;
pub use self::stbl::Stbl;
pub use self::stsd::Stsd;
pub use self::stdp::Stdp;
pub use self::stts::Stts;
pub use self::ctts::Ctts;
pub use self::cslg::Cslg;
pub use self::stss::Stss;
pub use self::stsh::Stsh;
pub use self::sdtp::Sdtp;
pub use self::edts::Edts;
pub use self::elst::Elst;
pub use self::dinf::Dinf;
pub use self::dref::Dref;
pub use self::stsz::Stsz;
pub use self::stz2::Stz2;
pub use self::stsc::Stsc;
pub use self::stco::Stco;
pub use self::co64::Co64;
pub use self::padb::Padb;
pub use self::subs::Subs;
pub use self::saiz::Saiz;
pub use self::saio::Saio;
pub use self::mvex::Mvex;
pub use self::mehd::Mehd;
pub use self::trex::Trex;
pub use self::moof::Moof;
pub use self::mfhd::Mfhd;
pub use self::traf::Traf;
pub use self::tfhd::Tfhd;
pub use self::trun::Trun;
pub use self::mfra::Mfra;
pub use self::tfra::Tfra;
pub use self::mfro::Mfro;
pub use self::tfdt::Tfdt;
pub use self::leva::Leva;
pub use self::trep::Trep;
pub use self::assp::Assp;
pub use self::sbgp::Sbgp;
pub use self::sgpd::Sgpd;
pub use self::udta::Udta;
pub use self::cprt::Cprt;
pub use self::tsel::Tsel;
pub use self::kind::Kind;
pub use self::meta::Meta;
pub use self::xml::Xml;
pub use self::bxml::Bxml;
pub use self::iloc::Iloc;
pub use self::pitm::Pitm;
pub use self::ipro::Ipro;
pub use self::iinf::Iinf;
pub use self::meco::Meco;
pub use self::mere::Mere;
pub use self::idat::Idat;
pub use self::iref::Iref;
pub use self::sinf::Sinf;
pub use self::frma::Frma;
pub use self::schm::Schm;
pub use self::schi::Schi;
pub use self::fiin::Fiin;
pub use self::paen::Paen;
pub use self::fpar::Fpar;
pub use self::fecr::Fecr;
pub use self::segr::Segr;
pub use self::gitn::Gitn;
pub use self::fire::Fire;
pub use self::strk::Strk;
pub use self::stri::Stri;
pub use self::strd::Strd;
pub use self::stsg::Stsg;
pub use self::rinf::Rinf;
pub use self::stvi::Stvi;
pub use self::styp::Styp;
pub use self::sidx::Sidx;
pub use self::ssix::Ssix;
pub use self::prft::Prft;
pub use self::cinf::Cinf;
pub use self::srpp::Srpp;
pub use self::feci::Feci;
pub use self::vmhd::Vmhd;
pub use self::smhd::Smhd;
pub use self::chnl::Chnl;
pub use self::dmix::Dmix;
pub use self::ludt::Ludt;
pub use self::hmhd::Hmhd;

/*** STATIC TYPES ***/
pub static ATOM_TYPES_NCHILDREN: &'static [&str] = &[ "ftyp", "mdat", "free", "skip", "tref", "idat", "frma", "segr", "styp", "feci" ];

pub static ATOM_TYPES_WCHILDREN: &'static [&str] = &[ "moov", "trak", "mdia", "minf", "stbl", "edts", "dinf", "mvex", "moof", "traf", "mfra", "udta", "meco", "sinf", "schi", "paen", "strk", "strd", "rinf", "cinf" ];

pub static FULL_ATOM_TYPES_NCHILDREN: &'static [&str] = &[ "pdin", "mvhd", "tkhd", "mdhd", "hdlr", "nmhd", "elng", "stdp", "stts", "ctts", "cslg", "stss", "stsh", "sdtp", "elst", "stsz", "stz2", "stsc", "stco", "co64", "padb", "subs", "saiz", "saio", "mehd", "trex", "mfhd", "tfhd", "trun", "tfra", "mfro", "tfdt", "leva", "assp", "sbgp", "cprt", "tsel", "kind", "xml ", "bxml", "iloc", "pitm", "mere", "schm", "fpar", "fecr", "gitn", "fire", "stri", "stsg", "sidx", "prft", "vmhd", "smhd", "chnl", "dmix", "ludt", "hmhd" ];

pub static FULL_ATOM_TYPES_WCHILDREN: &'static [&str] = &[ "trgr", "stsd", "dref", "trep", "sgpd", "meta", "ipro", "iinf", "iref", "fiin", "stvi", "ssix", "srpp" ];
